# Site
name: "Samarth Vanvi"
title: "Samarth Vanvi Blog"
description: "A place to get info about all of it"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'admin@samarthvanvi.in'
google_analytics: 'UA-166853210-1'
disqus: 'Samarth Blog'
sharethis: '<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5ebfb40c34ee1a00128dc65f&product=inline-share-buttons' async='async'></script>'

# Authors
authors:
  samarth:
    name: Samarth Vanvi
    display_name: Samarth Vanvi
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: i18vanvis@iimidr.ac.in
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  phani:
    name: Phani Ramadevu
    display_name: Phani Ramadevu
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: i18phanir@iimidr.ac.in
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman
