# Site
name: "Opinion Quill"
title: "Opinion Quill"
description: "Opinion Quill is an all-in-one Opinion writing, Question-Answer based and Debate Platform for anybody"
meta_description: "Opinion Quill is an all-in-one Opinion writing, Question-Answer based and Debate Platform for anybody"
logo: 'assets/images/logo_transparent.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'samarth@opinionquill.co.in'
google_analytics: 'UA-166853210-1'
disqus: 'samarthvanvi-in'
sharethis: '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5ebfb40c34ee1a00128dc65f&product=inline-share-buttons" async="async"></script>'

# Authors
authors:
  samarth:
    name: Samarth Vanvi
    display_name: Samarth Vanvi
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: i18vanvis@iimidr.ac.in
    web: https://samarthvanvi.in
    twitter: 
    description: "Samarth Vanvi is an investor in the Indian Stock Market. He is the Founder and Executive head of Vanvi Brokerage Firm. This website is a reflection of his personal and professional pursuits. Samarth is currently pursuing MBA from IIM Indore. In addition to his affinity in Equity and Derivatives Market, he also is very interested in Weaponology and Military History as reflected from his articles."
  phani:
    name: Phani Ramadevu
    display_name: Phani Ramadevu
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: i18phanir@iimidr.ac.in
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Phani Ramadevu is an undergraduate student at IIM Indore currently pursuing management, but this is no obstruction to his interest in physics and mathematics which he continues to study as an enthusiast."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman
